---
# tasks file for logstash
- name: Install Logstash CentOS
  yum:
    name: logstash
    state: latest
    update_cache: yes
  when = ansible_distribution == "CentOS"

- name: Run Daemlon-relod for Logstash (CentOS)
  systemd: daemon_reload=yes
  when: ansible_distribution == "CentOS"

- name: Enable Service Logstash (CentOS)
  systemd:
    name: logstash
    enabled: yes
  when: ansible_distribution == "CentOS"

- name: Ensure Logstash is Running (CentOS)
  systemd: state=started name=logstash
  when: ansible_distribution == "CentOS"
